export const CATEGORY_LABELS = {
  text: '文字・表記',
  word: 'Word構造',
  excel: 'Excel',
  safety: '成果品確認'
};

export const RULES = [
  { id: 'TXT-001', category: 'text', severity: 'error', engine: 'nbsp', title: 'NBSP（不可視空白）', description: 'U+00A0 の不可視空白を検出します。', appliesTo: ['word'] },
  { id: 'TXT-002', category: 'text', severity: 'confirm', engine: 'repeated-space', title: '連続する半角空白', description: '文章中の連続する半角空白を確認します。', appliesTo: ['word'] },
  { id: 'TXT-003', category: 'text', severity: 'confirm', engine: 'repeated-punctuation', title: '句読点の重複', description: '「、、」「。。」などの連続を検出します。', appliesTo: ['word'] },
  { id: 'TXT-004', category: 'text', severity: 'confirm', engine: 'punctuation-mix', title: '句読点表記の混在', description: '「、/，」「。/．」が文書内で混在していないか確認します。', appliesTo: ['word'] },
  { id: 'TXT-005', category: 'text', severity: 'confirm', engine: 'register-mix', title: '常体・敬体の混在', description: '「である調」と「です・ます調」の混在を簡易判定します。', appliesTo: ['word'] },

  { id: 'TXT-006', category: 'text', severity: 'error', engine: 'literal-replacement', title: '「発砲スチロール」', description: '一般的な誤記「発砲スチロール」を検出します。', appliesTo: ['word', 'excel'], replacements: [{ from: '発砲スチロール', to: '発泡スチロール' }] },
  { id: 'TXT-007', category: 'text', severity: 'confirm', engine: 'literal-replacement', title: 'NOx の大文字小文字', description: '窒素酸化物の一般的な表記「NOx」と異なる表記を確認します。', appliesTo: ['word', 'excel'], replacements: [{ from: 'Nox', to: 'NOx' }] },
  { id: 'TXT-008', category: 'text', severity: 'confirm', engine: 'literal-replacement', title: 'SDGs の大文字小文字', description: '「SDGs」の大文字小文字を確認します。', appliesTo: ['word', 'excel'], replacements: [{ from: 'SDGS', to: 'SDGs' }, { from: 'sdgs', to: 'SDGs' }] },
  { id: 'TXT-009', category: 'text', severity: 'confirm', engine: 'literal-replacement', title: 'MaaS の大文字小文字', description: '「MaaS」の大文字小文字を確認します。', appliesTo: ['word', 'excel'], replacements: [{ from: 'Maas', to: 'MaaS' }, { from: 'MAAS', to: 'MaaS' }] },
  { id: 'TXT-010', category: 'text', severity: 'confirm', engine: 'literal-replacement', title: '「の通り」', description: '公用文・ビジネス文書で「のとおり」とする方針の場合に確認します。', appliesTo: ['word'], replacements: [{ from: 'の通り', to: 'のとおり' }] },
  { id: 'TXT-011', category: 'text', severity: 'confirm', engine: 'literal-replacement', title: '「の為」', description: '形式的な用法の「為」をひらがなにする方針の場合に確認します。', appliesTo: ['word'], replacements: [{ from: 'の為', to: 'のため' }] },
  { id: 'TXT-012', category: 'text', severity: 'confirm', engine: 'literal-replacement', title: '「予め」', description: '「あらかじめ」と表記する方針の場合に確認します。', appliesTo: ['word'], replacements: [{ from: '予め', to: 'あらかじめ' }] },
  { id: 'TXT-013', category: 'text', severity: 'confirm', engine: 'literal-replacement', title: '「概ね」', description: '「おおむね」と表記する方針の場合に確認します。', appliesTo: ['word'], replacements: [{ from: '概ね', to: 'おおむね' }] },
  { id: 'TXT-014', category: 'text', severity: 'confirm', engine: 'literal-replacement', title: '「未だに」', description: '「いまだに」と表記する方針の場合に確認します。', appliesTo: ['word'], replacements: [{ from: '未だに', to: 'いまだに' }] },
  { id: 'TXT-015', category: 'text', severity: 'confirm', engine: 'literal-replacement', title: '「して頂く」', description: '補助動詞をひらがなにする方針の場合に確認します。', appliesTo: ['word'], replacements: [{ from: 'して頂く', to: 'していただく' }] },
  { id: 'TXT-016', category: 'text', severity: 'confirm', engine: 'literal-replacement', title: '「出来る」', description: '補助的な「できる」をひらがなにする方針の場合に確認します。', appliesTo: ['word'], replacements: [{ from: '出来る', to: 'できる' }] },
  { id: 'TXT-017', category: 'text', severity: 'confirm', engine: 'literal-replacement', title: '「然し」', description: '一般的な現代表記「しかし」を候補として提示します。', appliesTo: ['word'], replacements: [{ from: '然し', to: 'しかし' }] },
  { id: 'TXT-018', category: 'text', severity: 'confirm', engine: 'literal-replacement', title: '「たい肥」', description: '文書内で「堆肥」に統一する場合に確認します。', appliesTo: ['word', 'excel'], replacements: [{ from: 'たい肥', to: '堆肥' }] },
  { id: 'TXT-019', category: 'text', severity: 'confirm', engine: 'literal-replacement', title: '「ゴミ」', description: '文書内で「ごみ」に統一する場合に確認します。', appliesTo: ['word', 'excel'], replacements: [{ from: 'ゴミ', to: 'ごみ' }] },
  { id: 'TXT-020', category: 'text', severity: 'error', engine: 'literal-replacement', title: '「ストーカー式」', description: '焼却炉方式の「ストーカ式」の誤記候補を検出します。', appliesTo: ['word', 'excel'], replacements: [{ from: 'ストーカー式', to: 'ストーカ式' }] },
  { id: 'TXT-021', category: 'text', severity: 'confirm', engine: 'literal-replacement', title: 'コージェネレーション', description: '「コージェネレーション」と異なる表記を確認します。', appliesTo: ['word', 'excel'], replacements: [{ from: 'コジェネレーション', to: 'コージェネレーション' }] },
  { id: 'TXT-022', category: 'text', severity: 'confirm', engine: 'literal-replacement', title: 'J-クレジット表記', description: 'J-クレジットのハイフン表記を確認します。', appliesTo: ['word', 'excel'], replacements: [{ from: 'Jクレジット', to: 'J-クレジット' }, { from: 'J−クレジット', to: 'J-クレジット' }, { from: 'J－クレジット', to: 'J-クレジット' }] },
  { id: 'TXT-023', category: 'text', severity: 'confirm', engine: 'literal-replacement', title: '「再生エネルギー」', description: '「再生可能エネルギー」を意図していないか確認します。', appliesTo: ['word', 'excel'], replacements: [{ from: '再生エネルギー', to: '再生可能エネルギー' }] },
  { id: 'TXT-024', category: 'text', severity: 'confirm', engine: 'kw-case', title: 'kW の大文字小文字', description: '単位 kW の大文字小文字を確認します。', appliesTo: ['word', 'excel'] },
  { id: 'TXT-025', category: 'text', severity: 'confirm', engine: 'approx-redundancy', title: '「約…くらい」の重複', description: '「約」と「くらい」の重複表現を確認します。', appliesTo: ['word'] },
  { id: 'TXT-026', category: 'text', severity: 'confirm', engine: 'each-redundancy', title: '「各…ごとに」の重複', description: '「各」と「ごとに」が重複していないか確認します。', appliesTo: ['word'] },
  { id: 'TXT-027', category: 'text', severity: 'confirm', engine: 'literal-replacement', title: '「違和感を感じる」', description: '重複感のある表現を確認します。', appliesTo: ['word'], replacements: [{ from: '違和感を感じる', to: '違和感を覚える' }] },
  { id: 'TXT-028', category: 'text', severity: 'confirm', engine: 'literal-replacement', title: '「利用することができる」', description: '冗長になりやすい表現を確認します。', appliesTo: ['word'], replacements: [{ from: '利用することができる', to: '利用できる' }] },
  { id: 'TXT-029', category: 'text', severity: 'confirm', engine: 'literal-replacement', title: '「調査を実施した」', description: '簡潔化できる表現を確認します。', appliesTo: ['word'], replacements: [{ from: '調査を実施した', to: '調査した' }] },
  { id: 'TXT-030', category: 'text', severity: 'confirm', engine: 'double-negative', title: '二重否定', description: '「ないわけではない」等の二重否定を確認します。', appliesTo: ['word'] },
  { id: 'TXT-031', category: 'text', severity: 'confirm', engine: 'start-time-yori', title: '開始時刻の「より」', description: '開始点を示す「より」を「から」にできないか確認します。', appliesTo: ['word'] },
  { id: 'TXT-032', category: 'text', severity: 'confirm', engine: 'percent-width-mix', title: '％ / % の混在', description: '全角・半角のパーセント記号が混在していないか確認します。', appliesTo: ['word', 'excel'] },
  { id: 'TXT-033', category: 'text', severity: 'confirm', engine: 'co2-mix', title: 'CO2 / CO₂ の混在', description: '二酸化炭素表記の下付き有無が混在していないか確認します。', appliesTo: ['word', 'excel'] },
  { id: 'TXT-034', category: 'text', severity: 'confirm', engine: 'slash-width-mix', title: '／ / / の混在', description: 'スラッシュの全角・半角が混在していないか確認します。', appliesTo: ['word', 'excel'] },
  { id: 'TXT-035', category: 'text', severity: 'confirm', engine: 'year-format-mix', title: '和暦・西暦表記の混在', description: '和暦・西暦・併記形式が混在していないか簡易確認します。', appliesTo: ['word'] },
  { id: 'TXT-036', category: 'text', severity: 'confirm', engine: 'ton-unit-mix', title: 'トン / t の混在', description: '数値に続く質量単位「トン」「t」が混在していないか確認します。', appliesTo: ['word', 'excel'] },
  { id: 'TXT-037', category: 'text', severity: 'confirm', engine: 'tco2-mix', title: 't-CO2 / tCO2 の混在', description: 'CO2質量単位のハイフン有無が混在していないか確認します。', appliesTo: ['word', 'excel'] },
  { id: 'TXT-038', category: 'text', severity: 'confirm', engine: 'nth-day', title: '「第…日目」', description: '「第…日」へ簡潔化できるか確認します。', appliesTo: ['word'] },
  { id: 'TXT-039', category: 'text', severity: 'confirm', engine: 'literal-replacement', title: '「諸先生方」', description: '重複感のある敬称表現を確認します。', appliesTo: ['word'], replacements: [{ from: '諸先生方', to: '先生方' }] },
  { id: 'TXT-040', category: 'text', severity: 'confirm', engine: 'fullwidth-unit', title: '単位の全角英字', description: 'ｃｍ、ｋＷ、ｐｔ等の全角英字単位を確認します。', appliesTo: ['word', 'excel'] },

  { id: 'DOC-001', category: 'word', severity: 'confirm', engine: 'empty-table', title: '空の表', description: '内容が空の表が残っていないか確認します。', appliesTo: ['word'] },
  { id: 'DOC-002', category: 'word', severity: 'confirm', engine: 'red-text', title: '赤字の残存', description: '直接指定された赤色文字を検出します。', appliesTo: ['word'] },
  { id: 'DOC-003', category: 'safety', severity: 'confirm', engine: 'comments', title: 'コメントの残存', description: 'Wordコメントが残っていないか確認します。', appliesTo: ['word'] },
  { id: 'DOC-004', category: 'safety', severity: 'confirm', engine: 'tracked-changes', title: '変更履歴の残存', description: '変更履歴（挿入・削除等）が残っていないか確認します。', appliesTo: ['word'] },
  { id: 'DOC-005', category: 'word', severity: 'error', engine: 'broken-reference-text', title: '参照エラー文字列', description: 'Wordの「参照元が見つかりません」等のエラー文字列を検出します。', appliesTo: ['word'] },
  { id: 'DOC-006', category: 'word', severity: 'confirm', engine: 'missing-caption', title: '図表参照とキャプションの不一致', description: '本文が参照する図・表番号に対応するキャプションがあるか簡易確認します。', appliesTo: ['word'] },
  { id: 'DOC-007', category: 'word', severity: 'confirm', engine: 'caption-gap', title: '図表番号の欠番', description: '同一系列の図・表番号が不自然に飛んでいないか確認します。', appliesTo: ['word'] },
  { id: 'DOC-008', category: 'word', severity: 'confirm', engine: 'caption-duplicate', title: '図表番号の重複', description: '同じ図・表番号が複数回キャプションとして使われていないか確認します。', appliesTo: ['word'] },
  { id: 'DOC-009', category: 'word', severity: 'confirm', engine: 'heading-edge-space', title: '見出し端の余分な空白', description: '見出し先頭・末尾の半角/全角空白を確認します。', appliesTo: ['word'] },
  { id: 'DOC-010', category: 'word', severity: 'confirm', engine: 'paragraph-trailing-space', title: '段落末尾の余分な空白', description: '本文段落末尾に残った半角/全角空白を確認します。', appliesTo: ['word'] },

  { id: 'XLS-001', category: 'excel', severity: 'error', engine: 'error-cell', title: 'Excelエラー値', description: '#REF!、#DIV/0!、#VALUE!、#N/A 等を検出します。', appliesTo: ['excel'] },
  { id: 'XLS-002', category: 'excel', severity: 'error', engine: 'broken-formula-ref', title: '数式内の #REF!', description: '数式に壊れた参照が残っていないか確認します。', appliesTo: ['excel'] },
  { id: 'XLS-003', category: 'safety', severity: 'confirm', engine: 'hidden-sheet', title: '非表示シート', description: 'hidden / veryHidden のシートを列挙します。', appliesTo: ['excel'] },
  { id: 'XLS-004', category: 'safety', severity: 'confirm', engine: 'hidden-row', title: '非表示行', description: '非表示行が残っていないか確認します。', appliesTo: ['excel'] },
  { id: 'XLS-005', category: 'safety', severity: 'confirm', engine: 'hidden-col', title: '非表示列', description: '非表示列が残っていないか確認します。', appliesTo: ['excel'] },
  { id: 'XLS-006', category: 'excel', severity: 'confirm', engine: 'external-link', title: '外部リンク', description: 'ワークブック内の externalLinks パーツを検出します。', appliesTo: ['excel'] },
  { id: 'XLS-007', category: 'excel', severity: 'confirm', engine: 'formula-value-outlier', title: '数式列・行への直値混入', description: '上下または左右が数式のセルで、中央だけ直値のセルを検出します。', appliesTo: ['excel'] },
  { id: 'XLS-008', category: 'excel', severity: 'confirm', engine: 'formula-pattern-outlier', title: '数式パターンの局所不一致', description: '上下または左右の数式パターンが一致するのに中央だけ異なるセルを検出します。', appliesTo: ['excel'] },
  { id: 'XLS-009', category: 'excel', severity: 'confirm', engine: 'self-reference', title: '単純な自己参照', description: '数式が自身のセルを直接参照している可能性を検出します。', appliesTo: ['excel'] },
  { id: 'XLS-010', category: 'excel', severity: 'error', engine: 'missing-sheet-reference', title: '存在しないシートへの参照', description: '数式が存在しないシート名を参照していないか確認します。', appliesTo: ['excel'] }
];
